const path = require('path');
const express = require('express');
const rootDirectory = require('../utilities/path');

//get products array generated by admin.js
const adminData = require('./admin');

//to use the code from this file in server.js
const router = express.Router();


router.get('/', function(req, res){
    const products = adminData.products;

    console.log(products);
    
    res.render('shop', {
        pageTitle: 'Welcome!',
        pageWelcome: 'Welcome to my shop!',
        pageDescription: 'List of all the products:',
        listOfProducts: products
    });

    // res.sendFile(path.join(rootDirectory, 'views', 'shop.html'));
});

module.exports = router;